#!/usr/bin/env ruby
require './config/environment'

Invoice.quarter(ARGV[0].to_i, ARGV[1].to_i).each do |invoice|
  next if invoice.credit_note?

  country_code = if vat = invoice.customer_vat_number
      vat[0..1]
    else
      invoice.customer_country_code
    end

  exp_vat_rate = VatService.new.vat_rate(
    country_code: country_code,
    vat_registered: invoice.customer_vat_registered
  ).to_i

  vat_rate = (invoice.vat_rate || 0).to_i

  if exp_vat_rate != vat_rate
    puts "#{invoice.number} (#{invoice.stripe_customer_id}): #{exp_vat_rate} (#{country_code}) != #{vat_rate}"
  end
end
